name: dag_gettsim
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - anaconda-client
  - conda-build
  - conda-verify

  - jupyterlab
  - matplotlib
  - networkx
  - pandas
  - pre-commit
  - pyyaml
  - pytest
  - pytest-cov
  - pytest-xdist

  - restructuredtext_lint
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - bump2version
